# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f6cf1ca46a85334fca1767070882786a3bd87ea1271e646b8973d86935fa18c97cfc1385f53d4dba896329a053ce4c45c61ce95f77f14bb190ac4f18202a243

test:
  secret_key_base: c6e40b3836142d926e2ca99e0486e62474e7c7613b153e6c3fc1b3efeabd742a7e8dc5fad8be98d2297018f34f29a7a31d7c1c876196168ebf8280957d255a9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
